/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import NapakalakiGame.*;
/**
 *
 * @author l
 */
public class NapakalakiView extends javax.swing.JFrame {

    
    private Napakalaki napakalakiModel; 
    private boolean hacombatido=false;
    
    public void setNapakalaki(Napakalaki n){
        
        napakalakiModel=n;
        playerView2.setPlayer(napakalakiModel.getCurrentPlayer());
        playerView2.setMakeVisible(true);
        playerView2.setBuyLevels(true);
        playerView2.setDiscardTreasures(true);
        monsterView2.setVisible(false);
        nextTurn.setEnabled(false);
        Win.setVisible(false);
        Win.setText("Ganaste!!!!!!!!!!!");
        meetMonster.setEnabled(true);
        combat.setEnabled(false);
        nextTurn.setEnabled(false);
        monsterView2.setMonsterView(napakalakiModel.getCurrentMonster());
        playerView2.setNapakalki(n);
        repaint();
    }
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meetMonster = new javax.swing.JButton();
        nextTurn = new javax.swing.JButton();
        combat = new javax.swing.JButton();
        Win = new javax.swing.JTextField();
        playerView2 = new GUI.PlayerView();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadopelea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        monsterView2 = new GUI.MonsterView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        meetMonster.setText("Meet the Moster!");
        meetMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetMonsterActionPerformed(evt);
            }
        });

        nextTurn.setText("Next turn");
        nextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnActionPerformed(evt);
            }
        });

        combat.setText("Combat!");
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });

        resultadopelea.setColumns(20);
        resultadopelea.setRows(5);
        jScrollPane1.setViewportView(resultadopelea);

        jLabel1.setText("resultado combate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playerView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monsterView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(meetMonster)
                .addGap(87, 87, 87)
                .addComponent(combat)
                .addGap(102, 102, 102)
                .addComponent(nextTurn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Win, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(monsterView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(playerView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(meetMonster)
                        .addComponent(combat)
                        .addComponent(nextTurn))
                    .addComponent(Win, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meetMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetMonsterActionPerformed
        monsterView2.setVisible(true);
        playerView2.setMakeVisible(false);
        playerView2.setBuyLevels(false);
        combat.setEnabled(true);
         if(hacombatido)
            combat.setEnabled(false);
    }//GEN-LAST:event_meetMonsterActionPerformed

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
        playerView2.setDiscardTreasures(true);
        CombatResult combatResult;
        combatResult = napakalakiModel.developCombat();
        if(combatResult==CombatResult.WinAndWinGame){
            Win.setVisible(true);
            playerView2.setVisible(false);
            monsterView2.setVisible(false);
            combat.setVisible(false);
            nextTurn.setVisible(false);
            meetMonster.setVisible(false);
        }
        playerView2.setPlayer(napakalakiModel.getCurrentPlayer());
        playerView2.setMakeVisible(true);
        playerView2.setDiscardTreasures(true);
        combat.setEnabled(false);
        nextTurn.setEnabled(true);
        resultadopelea.setVisible(true);
        jLabel1.setVisible(true);
        meetMonster.setEnabled(false);
        hacombatido=true;
        playerView2.setBuyLevels(true);
        
        switch(combatResult){
            case WinAndWinGame:
                this.resultadopelea.setText("Ganas el Combate y la partida");                 
            break;
            case Win:
                this.resultadopelea.setText("Ganas el Combate");
            break;
            case Lose:
                this.resultadopelea.setText("Pierdes el Combate y tienes que cumplir el mal rollo");
            break;
            case LoseAndEscape:
                this.resultadopelea.setText("Pierdes el combate y consigues\n escapar");
            break;
            case LoseAndDie:
                this.resultadopelea.setText("Pierdes el combate y mueres");
            break;
        }
        
    }//GEN-LAST:event_combatActionPerformed

    private void nextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnActionPerformed
        // TODO add your handling code here:
        if(napakalakiModel.nextTurn()){
            this.setNapakalaki(napakalakiModel);
            resultadopelea.setVisible(false);
            jLabel1.setVisible(false);
            meetMonster.setEnabled(true);
            hacombatido=false;
        }
    }//GEN-LAST:event_nextTurnActionPerformed

   
    public void showView(){
        this.setVisible(true);
        resultadopelea.setVisible(false);
        jLabel1.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Win;
    private javax.swing.JButton combat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton meetMonster;
    private GUI.MonsterView monsterView2;
    private javax.swing.JButton nextTurn;
    private GUI.PlayerView playerView2;
    private javax.swing.JTextArea resultadopelea;
    // End of variables declaration//GEN-END:variables
}
