/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUIQytetet;
import modeloqytetet.Dado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modeloqytetet.*;

/**
 *
 * @author felix
 */
public class ControladorQytetet extends javax.swing.JFrame {

    public Qytetet modeloQytetet;
    /**
     * Creates new form ControladorQytetet
     */
    public ControladorQytetet() {
        initComponents();
        this.carceldado.setEnabled(false);
        this.carcelpagando.setEnabled(false);
        this.aplicarsorpresa.setEnabled(false);
        this.comprarpropiedad.setEnabled(false);
        this.siguientejugador.setEnabled(false);
    }
    
    public void actualizar(Qytetet model){
        this.modeloQytetet = model;
        this.habilitarComenzarTurno();
        this.vistaQytetet1.actualizar(modeloQytetet);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaQytetet1 = new GUIQytetet.VistaQytetet();
        carceldado = new javax.swing.JButton();
        carcelpagando = new javax.swing.JButton();
        jugar = new javax.swing.JButton();
        comprarpropiedad = new javax.swing.JButton();
        aplicarsorpresa = new javax.swing.JButton();
        siguientejugador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        carceldado.setText("Salir carcel dado");
        carceldado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carceldadoActionPerformed(evt);
            }
        });

        carcelpagando.setText("Salir carcel pagando");
        carcelpagando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carcelpagandoActionPerformed(evt);
            }
        });

        jugar.setText("JUGAR");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        comprarpropiedad.setText("Comprar propiedad");
        comprarpropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarpropiedadActionPerformed(evt);
            }
        });

        aplicarsorpresa.setText("Aplicar Sorpresa");
        aplicarsorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarsorpresaActionPerformed(evt);
            }
        });

        siguientejugador.setText("SIGUIENTE JUGADOR");
        siguientejugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientejugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vistaQytetet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carceldado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carcelpagando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comprarpropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aplicarsorpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siguientejugador, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(vistaQytetet1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carceldado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carcelpagando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(comprarpropiedad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aplicarsorpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguientejugador, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carceldadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carceldadoActionPerformed
        // TODO add your handling code here:
        boolean resultado = modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.TIRANDODADO);
        this.carceldado.setEnabled(false);
        this.carcelpagando.setEnabled(false);

        if(resultado){
         JOptionPane.showMessageDialog(this, "Sales de la cárcel");
         this.jugar.setEnabled(true);
        }else {
         JOptionPane.showMessageDialog(this, "NO sales de la carcel");
         this.siguientejugador.setEnabled(true);
         }
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_carceldadoActionPerformed

    private void carcelpagandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carcelpagandoActionPerformed
        // TODO add your handling code here:
        boolean resultado = modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.PAGANDOLIBERTAD);
        this.carceldado.setEnabled(false);
        this.carcelpagando.setEnabled(false);

        if(resultado){
         JOptionPane.showMessageDialog(this, "Sales de la cárcel");
         this.jugar.setEnabled(true);
        }else {
         JOptionPane.showMessageDialog(this, "NO sales de la carcel");
         this.siguientejugador.setEnabled(true);
         }
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_carcelpagandoActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // TODO add your handling code here:
        boolean jugar1 = modeloQytetet.jugar();
        this.jugar.setEnabled(false);
        
        if(jugar1){
            this.comprarpropiedad.setEnabled(false);
        }else
            this.comprarpropiedad.setEnabled(true);
        
        if(!modeloQytetet.getJugadorActual().getEncarcelado()){
            this.carceldado.setEnabled(false);
            this.carcelpagando.setEnabled(false);
        }else{
            this.carceldado.setEnabled(false);
            this.carcelpagando.setEnabled(false);
        }
        
        if(modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.SALIDA      ||
           modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.CARCEL      ||
           modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.IMPUESTO    ||
           modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.JUEZ        ||
           modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.PARKING     ||
           modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.SORPRESA){
        
            this.comprarpropiedad.setEnabled(false);
        }
            
        
        if(modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.SORPRESA){
            this.siguientejugador.setEnabled(false);
            this.aplicarsorpresa.setEnabled(true);
        }else
            this.siguientejugador.setEnabled(true);
        
        this.vistaQytetet1.actualizar(modeloQytetet);
        
    }//GEN-LAST:event_jugarActionPerformed

    public void habilitarComenzarTurno(){
        this.comprarpropiedad.setEnabled(false);
        this.siguientejugador.setEnabled(false);
        this.aplicarsorpresa.setEnabled(false);
        if(modeloQytetet.getJugadorActual().getEncarcelado()){
            this.carcelpagando.setEnabled(true);
            this.carceldado.setEnabled(true);
        }
        else
            this.jugar.setEnabled(true);
    } 
    
    private void comprarpropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarpropiedadActionPerformed
        // TODO add your handling code here:
        boolean comprarTituloPropiedad = modeloQytetet.comprarTituloPropiedad();
        
        if(comprarTituloPropiedad){
            
        }
        this.comprarpropiedad.setEnabled(false);
        this.jugar.setEnabled(false);
        this.siguientejugador.setEnabled(true);
        
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_comprarpropiedadActionPerformed

    private void aplicarsorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarsorpresaActionPerformed
        // TODO add your handling code here:
        this.aplicarsorpresa.setEnabled(false);
        boolean aplicarSorpresa = modeloQytetet.aplicarSorpresa();
        if(aplicarSorpresa){
            //tiene propietario
        }
        this.siguientejugador.setEnabled(true);
        this.vistaQytetet1.actualizar(modeloQytetet);
    }//GEN-LAST:event_aplicarsorpresaActionPerformed

    private void siguientejugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientejugadorActionPerformed
        // TODO add your handling code here:
        Jugador siguienteJugador = modeloQytetet.siguienteJugador();
        
        this.siguientejugador.setEnabled(false);
        this.vistaQytetet1.actualizar(modeloQytetet);
        
        if(!modeloQytetet.getJugadorActual().getEncarcelado()){
            this.jugar.setEnabled(true);
            this.carceldado.setEnabled(false);
            this.carcelpagando.setEnabled(false);
        }else{
            this.jugar.setEnabled(false);
            this.carceldado.setEnabled(true);
            this.carcelpagando.setEnabled(true);
        }
        
        this.habilitarComenzarTurno();
        
        
    }//GEN-LAST:event_siguientejugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        ControladorQytetet controladorQytetet = new ControladorQytetet();
        controladorQytetet.setVisible(true);
        CapturaNombreJugadores capturaNombres = new CapturaNombreJugadores(controladorQytetet, true);
        ArrayList<String> nombres= capturaNombres.obtenerNombres();
        Qytetet q = Qytetet.getInstance();
        q.inicializarJuego(nombres);
        Dado.createInstance(controladorQytetet);
        controladorQytetet.actualizar(q);
        //controladorQytetet.habilitarComenzarTurno();
        controladorQytetet.actualizar(q); 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicarsorpresa;
    private javax.swing.JButton carceldado;
    private javax.swing.JButton carcelpagando;
    private javax.swing.JButton comprarpropiedad;
    private javax.swing.JButton jugar;
    private javax.swing.JButton siguientejugador;
    private GUIQytetet.VistaQytetet vistaQytetet1;
    // End of variables declaration//GEN-END:variables
}
